# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/authentication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/authentication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/authentication.proto\x12\x0e\x61uthentication\x1a\x1cgoogle/protobuf/struct.proto\"L\n\x12GenerateOTPRequest\x12\x10\n\x08\x63lientID\x18\x01 \x01(\t\x12\x14\n\x0c\x63lientSecret\x18\x02 \x01(\t\x12\x0e\n\x06rollNo\x18\x03 \x01(\x05\"&\n\x13GenerateOTPResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"W\n\x10VerifyOTPRequest\x12\x10\n\x08\x63lientID\x18\x01 \x01(\t\x12\x14\n\x0c\x63lientSecret\x18\x02 \x01(\t\x12\x0e\n\x06rollNo\x18\x03 \x01(\x05\x12\x0b\n\x03otp\x18\x04 \x01(\x05\"N\n\x11VerifyOTPResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12(\n\x07\x44\x65tails\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct2\xba\x01\n\x0e\x41uthentication\x12V\n\x0bGenerateOTP\x12\".authentication.GenerateOTPRequest\x1a#.authentication.GenerateOTPResponse\x12P\n\tVerifyOTP\x12 .authentication.VerifyOTPRequest\x1a!.authentication.VerifyOTPResponseB\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_GENERATEOTPREQUEST']._serialized_start=77
  _globals['_GENERATEOTPREQUEST']._serialized_end=153
  _globals['_GENERATEOTPRESPONSE']._serialized_start=155
  _globals['_GENERATEOTPRESPONSE']._serialized_end=193
  _globals['_VERIFYOTPREQUEST']._serialized_start=195
  _globals['_VERIFYOTPREQUEST']._serialized_end=282
  _globals['_VERIFYOTPRESPONSE']._serialized_start=284
  _globals['_VERIFYOTPRESPONSE']._serialized_end=362
  _globals['_AUTHENTICATION']._serialized_start=365
  _globals['_AUTHENTICATION']._serialized_end=551
# @@protoc_insertion_point(module_scope)
