# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lynx_auth_pb2 as lynx__auth__pb2


class AuthenticationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateOTP = channel.unary_unary(
                '/authentication.Authentication/GenerateOTP',
                request_serializer=lynx__auth__pb2.GenerateOTPRequest.SerializeToString,
                response_deserializer=lynx__auth__pb2.GenerateOTPResponse.FromString,
                )
        self.VerifyOTP = channel.unary_unary(
                '/authentication.Authentication/VerifyOTP',
                request_serializer=lynx__auth__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=lynx__auth__pb2.VerifyOTPResponse.FromString,
                )


class AuthenticationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateOTP,
                    request_deserializer=lynx__auth__pb2.GenerateOTPRequest.FromString,
                    response_serializer=lynx__auth__pb2.GenerateOTPResponse.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=lynx__auth__pb2.VerifyOTPRequest.FromString,
                    response_serializer=lynx__auth__pb2.VerifyOTPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authentication.Authentication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Authentication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/GenerateOTP',
            lynx__auth__pb2.GenerateOTPRequest.SerializeToString,
            lynx__auth__pb2.GenerateOTPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authentication.Authentication/VerifyOTP',
            lynx__auth__pb2.VerifyOTPRequest.SerializeToString,
            lynx__auth__pb2.VerifyOTPResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
