# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lynx_auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flynx_auth.proto\x12\x0e\x61uthentication\x1a\x1cgoogle/protobuf/struct.proto\"L\n\x12GenerateOTPRequest\x12\x10\n\x08\x63lientID\x18\x01 \x01(\t\x12\x14\n\x0c\x63lientSecret\x18\x02 \x01(\t\x12\x0e\n\x06rollNo\x18\x03 \x01(\x05\"&\n\x13GenerateOTPResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"W\n\x10VerifyOTPRequest\x12\x10\n\x08\x63lientID\x18\x01 \x01(\t\x12\x14\n\x0c\x63lientSecret\x18\x02 \x01(\t\x12\x0e\n\x06rollNo\x18\x03 \x01(\x05\x12\x0b\n\x03otp\x18\x04 \x01(\x05\"N\n\x11VerifyOTPResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12(\n\x07\x44\x65tails\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct2\xba\x01\n\x0e\x41uthentication\x12V\n\x0bGenerateOTP\x12\".authentication.GenerateOTPRequest\x1a#.authentication.GenerateOTPResponse\x12P\n\tVerifyOTP\x12 .authentication.VerifyOTPRequest\x1a!.authentication.VerifyOTPResponseB\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lynx_auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\001.'
  _globals['_GENERATEOTPREQUEST']._serialized_start=65
  _globals['_GENERATEOTPREQUEST']._serialized_end=141
  _globals['_GENERATEOTPRESPONSE']._serialized_start=143
  _globals['_GENERATEOTPRESPONSE']._serialized_end=181
  _globals['_VERIFYOTPREQUEST']._serialized_start=183
  _globals['_VERIFYOTPREQUEST']._serialized_end=270
  _globals['_VERIFYOTPRESPONSE']._serialized_start=272
  _globals['_VERIFYOTPRESPONSE']._serialized_end=350
  _globals['_AUTHENTICATION']._serialized_start=353
  _globals['_AUTHENTICATION']._serialized_end=539
# @@protoc_insertion_point(module_scope)
